[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/create"
  to = "/create.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200
